version: '{build}'
image: Visual Studio 2015
platform:
  - x86
  #- x64
environment:
  global:
    WHEELHOUSE_UPLOADER_REGION: IAD
    WHEELHOUSE_UPLOADER_USERNAME: pystan-worker
    WHEELHOUSE_UPLOADER_SECRET:
      secure: cqdCOlelH3UdBVv+FyD4nNfT5X5bB2OwqehwkxqMABKcHy1H4+t8v3jVVvTxV7uq

  matrix:
    #- CONDA: 27
    - CONDA: 35
    #- CONDA: 36

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""
  - SET "CONDAPATH=conda%CONDA%"
  - if %CONDA%==27 (SET "CONDAPATH=conda")
  - if %PLATFORM%==x64 (SET "CONDAPATH=%CONDAPATH%-x64")
  - SET "PATH=C:\\mingw-w64\\x86_64-7.3.0-posix-seh-rt_v5-rev0;%PATH%"
  #- ps: "ls \"C:\\mingw-w64\\x86_64-7.3.0-posix-seh-rt_v5-rev0\""
  #- gcc --version
  #- SET "PATH=C:\\Miniconda%PY%;C:\\Miniconda%PY%\\Scripts;C:\\Miniconda%PY%\\bin;%PATH%"
  - CALL "C:\\Mini%CONDAPATH%\\Scripts\\conda.exe" info --envs
  - if %CONDA%==35 (CALL "C:\\Mini%CONDAPATH%\\Scripts\\activate.bat" root)
  - if NOT %CONDA%==35 (CALL "C:\\Mini%CONDAPATH%\\Scripts\\activate.bat" base)
  # checkout submodules
  - git submodule update --init --recursive
  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - conda config --set always_yes yes --set changeps1 no
  #- conda config --add channels conda-forge
  - conda update -q conda
  - conda update python
  - conda install setuptools libpython m2w64-toolchain -c msys2 -q
  # numpy==1.15.0 had problems with mkl_fft (date 2018-07-29)
  - conda install numpy cython scipy matplotlib pandas -q
  #- python -c "import os, distutils; f=open(os.path.join((os.path.split(distutils.__file__))[0], 'distutils.cfg'), 'w'); f.write('[build]\ncompiler=mingw32');f.close()"
  - python -c "import numpy as np; print('numpy imported succesfull')"
  - gcc --version
  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - python -m pip install --disable-pip-version-check --upgrade pip

  # Install the build dependencies of the project.
  - pip install -r ./continuous_integration/appveyor/requirements.txt
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

build_script:
  - ECHO "Starting to build the wheel"
  # build the wheel and install it
  - python setup.py bdist_wheel bdist_wininst
  - ps: "ls ."
  - dir dist
  - dir build

  - ECHO "Install generated wheel to test it"
  # Install the generated wheel package to test it
  - pip install --pre --no-index --find-links dist/ pystan

test_script:
  # Change to a non-source folder to make sure we run the tests on the
  # installed library.
  - mkdir empty_folder
  - cd empty_folder
  - SET "JOBLIB_MULTIPROCESSING=1"
  - ECHO "Starting the tests"
  - "python -c \"import nose; nose.main()\" -v pystan.tests"
  # Move back to the project folder
  - "cd .."

after_test:
  - ECHO "After tests - Building wheels"
  # If tests are successful, create binary packages for the project.
  # TODO: may need to set PBR_VERSION, submodules often confuse pbr
  - python setup.py bdist_wheel"
  - ps: "ls dist"
  # APPVEYOR_REPO_TAG will be true if commit is tagged
  - "IF /I %APPVEYOR_REPO_TAG%==true (pip install wheelhouse-uploader)"
  - "IF /I %APPVEYOR_REPO_TAG%==true (python -m wheelhouse_uploader upload --local-folder=dist --no-ssl-check --no-update-index --region=%WHEELHOUSE_UPLOADER_REGION% wheels)"
